export const langArr = {
  en: {
    headerPost: 'Front End Developer',
    headerHome: 'Home',
    headerAbout: 'About',
    headerExp: 'Experience',
    headerPortf: 'Portfolio',
    headerContact: 'Contact',
    homeSubtitle: 'Hi there !',
    homeTitle: 'I\'M <span>Shamil Magomedov</span>',
    homeText: 'Experience in frontend 2.5 years (1 year in a team), I make up complex layouts from Figma/XD/PSD. I\'m doing email templates / email signatures for all platforms and css animations / GSAP animations.<br> I have experience with bootstrap and tailwindcss. I use a modular and functional approach in my javaScript code and I use ESLint by airbnb. In html and css I use component approach with BEM methodology.',
    homeBtn: 'About me',
    headingAbout: '<span>About</span> me',
    headingExp: 'My <span>experience</span>',
    headingPortf: 'My <span>portfolio</span>',
    headingContact: '<span>Contact</span> me',
    aboutName: '<span>Name :</span> Shamil Magomedov',
    aboutAge: '<span>Age :</span> 24',
    aboutQual: '<span>Qualification :</span> BCS',
    aboutPost: '<span>Post :</span> Front End Developer',
    aboutLang: '<span>Language :</span> Russian / English',
    aboutDownload: 'Download CV',
    aboutHire: 'Hire me',
    aboutExpYears: 'Years Of Experience',
    aboutCompleted: 'Project completed',
    aboutClients: 'Happy clients',
    aboutCourses: 'Professional courses',
    expTextOne: 'Web Site Development Of Any Complexity ( Landing Pages, Multipage Sites ), Frontend, Email Templates / Email Signatures, Css Animation / GreenSock Animation, Legacy Sites Support, Etc ...',
    expTextTwo: 'Support And Development Of Large Brand Sites ( J7sok, Frutonyanya, Raiffeisen-Life, Renlife, Fetaxa, Adrenalinerush, Wella, KollektivX, Mexx, Lays, Etc... ), Frontend, Email Templates, GSAP / Css Animation, Legacy Sites Support.',
    expTextThree: 'Web Site Development Of Any Complexity ( Landing Pages, Multipage Sites ), Frontend, Email Templates / Email Signatures, Css Animation / GreenSock Animation, Legacy Sites Support, Etc ...',
    expTitle: 'Front End Development',
    contactInfo: 'Contact info',
    contactAddress: 'Makhachkala, Russia - 367010.',
    contactBtn: 'Send',
    formName: 'Name',
    formEmail: 'Email',
    formProject: 'Project',
    formMessage: 'Message',
    formTimer: 'Wait <span class="feedback__timer-value">30</span> seconds to submit the form again.',
    errorText: 'Letter sending error',
    errorBtn: 'Resend',
    successText: 'Letter successfully sended',
    successBtn: 'Awesome !'
  },
  ru: {
    headerPost: 'Front End Разработчик',
    headerHome: 'Главная',
    headerAbout: 'Обо мне',
    headerExp: 'Опыт',
    headerPortf: 'Портфолио',
    headerContact: 'Контакты',
    homeSubtitle: 'Всем привет !',
    homeTitle: 'Я <span>Шамиль Магомедов</span>',
    homeText: 'Опыт работы во фронтенде 2,5 года (1 год в команде), верстаю сложные макеты из Figma/XD/PSD. Я делаю шаблоны электронной почты / подписи электронной почты для всех платформ и анимацию css / анимацию GSAP. У меня есть опыт работы с bootstrap и tailwindcss.<br> Я использую модульный и функциональный подход в своем коде JavaScript и использую ESLint от airbnb. В html и css использую компонентный подход с методологией БЭМ.',
    homeBtn: 'Обо мне',
    headingAbout: '<span>Обо</span> мне',
    headingExp: 'Мой <span>опыт</span>',
    headingPortf: 'Моё <span>портфолио</span>',
    headingContact: '<span>Свяжитесь</span> со мной',
    aboutName: '<span>Имя :</span> Шамиль Магомедов',
    aboutAge: '<span>Возраст</span> 24',
    aboutQual: '<span>Квалификация :</span> БКН',
    aboutPost: '<span>Post :</span> Front End Разработчик',
    aboutLang: '<span>Язык :</span> Русский / Английский',
    aboutDownload: 'Скачать CV',
    aboutHire: 'Нанять',
    aboutExpYears: 'Лет опыта',
    aboutCompleted: 'Завершенных проектов',
    aboutClients: 'Счастливых клиентов',
    aboutCourses: 'Проф&nbsp;-&nbsp;<i style="text-transform: lowercase; font-style: normal;">х</i><br>курсов',
    expTextOne: 'Разработка сайтов любой сложности (Landing Pages, Multipage Sites), Frontend, Email шаблоны / Email подписи, Css анимация / GreenSock анимация, поддержка старых сайтов, <span style="text-transform: lowercase;">и т.д.</span>',
    expTextTwo: 'Поддержка и развитие сайтов крупных брендов ( J7sok, Frutonyanya, Raiffeisen-Life, Renlife, Fetaxa, Adrenalinerush, Wella, KollektivX, Mexx, Lays <span style="text-transform: lowercase;">и т.д.</span>), Frontend, Email шаблоны, GSAP / Css анимация, поддержка старых сайтов.',
    expTextThree: 'Разработка сайтов любой сложности (Landing Pages, Multipage Sites), Frontend, Email шаблоны / Email подписи, Css анимация / GreenSock анимация, поддержка старых сайтов, <span style="text-transform: lowercase;">и т.д.</span>',
    expTitle: 'Front End Разработка',
    contactInfo: 'Контактная информация',
    contactAddress: 'Махачкала, Россия - 367010.',
    contactBtn: 'Отправить',
    formName: 'Имя',
    formEmail: 'Почта',
    formProject: 'Проект',
    formMessage: 'Сообщение',
    formTimer: 'Подождите <span class="feedback__timer-value">30</span> секунд, чтобы отправить форму заного.',
    errorText: 'Ошибка отправки письма',
    errorBtn: 'Отправить ещё раз',
    successText: 'Письмо успешно отправлено',
    successBtn: 'Круто !'
  }
};
